package interfaz;

/**
 *
 * @author camilafermosoiglesias
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method ss called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        NuevaSimulacion = new javax.swing.JButton();
        AgregarCiudad = new javax.swing.JButton();
        EliminarCiudad = new javax.swing.JButton();
        GuardarGrafo = new javax.swing.JButton();
        CargarGrafo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        Exit.setBackground(new java.awt.Color(0, 153, 255));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        NuevaSimulacion.setBackground(new java.awt.Color(255, 51, 51));
        NuevaSimulacion.setText("Nueva Simulación");
        NuevaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaSimulacionActionPerformed(evt);
            }
        });
        getContentPane().add(NuevaSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 30));

        AgregarCiudad.setText("Agregar Ciudad");
        AgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, 30));

        EliminarCiudad.setText("Eliminar Ciudad");
        EliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        GuardarGrafo.setText("Guardar Grafo");
        GuardarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, 30));

        CargarGrafo.setText("Cargar Grafo");
        CargarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(CargarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void NuevaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaSimulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaSimulacionActionPerformed

    private void AgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCiudadActionPerformed

    private void EliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarCiudadActionPerformed

    private void GuardarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarGrafoActionPerformed

    private void CargarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCiudad;
    private javax.swing.JButton CargarGrafo;
    private javax.swing.JButton EliminarCiudad;
    private javax.swing.JButton Exit;
    private javax.swing.JButton GuardarGrafo;
    private javax.swing.JButton NuevaSimulacion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
